### PR TITLE
NVM NOT DRAFT: Remove bootloader from kernel

### PR DESCRIPTION
**Pull request by laurinyev**

### CODE REVIEW

**Review by kevinalavik — APPROVED** [review]
Awesome!!

**Comment by laurinyev** [comment]
shit im a lil late

**Comment by cre0z** [comment]
What is this for?

**Comment by laurinyev** [comment]
> What is this for?

removing the bootloader code KEvin added in, replacing it with a pure EFI(no BL) target(can be removed later)

**Review by cre0z — APPROVED** [review]

**Pull request merged**
